-- 账号启用链接与账号通知邮件
-- 适用于已有数据、需要保留的环境；可重复执行。
-- 新环境使用 ry_20260819_postgresql.sql（已包含本脚本内容）。

-- 1. 账号启用时间：NULL 表示“待启用”（管理员已建号，员工还没通过邮件链接设置密码）
ALTER TABLE IF EXISTS sys_user
    ADD COLUMN IF NOT EXISTS activate_time TIMESTAMP DEFAULT NULL;
COMMENT ON COLUMN sys_user.activate_time IS '账号启用时间；NULL 表示待启用，员工尚未通过邮件链接设置密码';

-- 存量账号都已经能正常登录，视为已启用
UPDATE sys_user
SET activate_time = COALESCE(pwd_update_date, create_time, CURRENT_TIMESTAMP)
WHERE activate_time IS NULL;
Ï
-- 2. 邮件一次性链接凭证：数据库只存 SHA-256 哈希，不存原文
CREATE TABLE IF NOT EXISTS sys_account_link (
  link_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id       BIGINT       NOT NULL,
  link_type     VARCHAR(20)  NOT NULL,
  token_hash    CHAR(64)     NOT NULL,
  expire_time   TIMESTAMP    NOT NULL,
  used_time     TIMESTAMP    DEFAULT NULL,
  revoked_time  TIMESTAMP    DEFAULT NULL,
  create_by     VARCHAR(64)  DEFAULT '',
  create_time   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (link_id)
);
COMMENT ON TABLE  sys_account_link IS '账号邮件一次性链接：启用账号等；只保存凭证哈希，提交成功或重新发送后作废';
COMMENT ON COLUMN sys_account_link.link_type    IS '链接类型：ACTIVATE 启用账号';
COMMENT ON COLUMN sys_account_link.token_hash   IS '链接凭证 SHA-256 十六进制哈希';
COMMENT ON COLUMN sys_account_link.used_time    IS '使用时间；非空表示已使用';
COMMENT ON COLUMN sys_account_link.revoked_time IS '作废时间；重新发送、停用账号时写入';

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_account_link_token_hash ON sys_account_link (token_hash);
CREATE INDEX IF NOT EXISTS idx_sys_account_link_user ON sys_account_link (user_id);
