-- FiveTech Dashboard menu translations
-- Safe migration: does not delete or rebuild existing business tables.
-- Execute this script after sys_menu has been created.

BEGIN;

CREATE TABLE IF NOT EXISTS sys_menu_i18n (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  menu_id     BIGINT NOT NULL,
  locale      VARCHAR(20) NOT NULL,
  menu_name   VARCHAR(100) NOT NULL,
  remark      VARCHAR(500) DEFAULT '',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_sys_menu_i18n_menu_locale UNIQUE (menu_id, locale),
  CONSTRAINT fk_sys_menu_i18n_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(menu_id) ON DELETE CASCADE
);

COMMENT ON TABLE sys_menu_i18n IS '菜单多语言名称表';
COMMENT ON COLUMN sys_menu_i18n.menu_id IS 'sys_menu.menu_id';
COMMENT ON COLUMN sys_menu_i18n.locale IS '语言代码：zh-CN、zh-TW、en-US';

-- Only insert translations for menus that exist in the current database.
-- This keeps the migration safe when optional menus were removed.
INSERT INTO sys_menu_i18n (menu_id, locale, menu_name, remark)
SELECT v.menu_id, v.locale, v.menu_name, v.remark
FROM (VALUES
  (1,    'zh-CN', '系统管理', '系统管理目录'),
  (1,    'zh-TW', '系統管理', '系統管理目錄'),
  (1,    'en-US', 'System Management', 'System management'),
  (2,    'zh-CN', '系统监控', '系统监控目录'),
  (2,    'zh-TW', '系統監控', '系統監控目錄'),
  (2,    'en-US', 'System Monitoring', 'System monitoring'),
  (3,    'zh-CN', '系统工具', '系统工具目录'),
  (3,    'zh-TW', '系統工具', '系統工具目錄'),
  (3,    'en-US', 'System Tools', 'System tools'),
  (100,  'zh-CN', '用户管理', '用户管理菜单'),
  (100,  'zh-TW', '使用者管理', '使用者管理選單'),
  (100,  'en-US', 'User Management', 'User management'),
  (101,  'zh-CN', '角色管理', '角色管理菜单'),
  (101,  'zh-TW', '角色管理', '角色管理選單'),
  (101,  'en-US', 'Role Management', 'Role management'),
  (102,  'zh-CN', '权限管理', '权限管理菜单'),
  (102,  'zh-TW', '權限管理', '權限管理選單'),
  (102,  'en-US', 'Permission Management', 'Permission management'),
  (103,  'zh-CN', '部门管理', '部门管理菜单'),
  (103,  'zh-TW', '部門管理', '部門管理選單'),
  (103,  'en-US', 'Department Management', 'Department management'),
  (108,  'zh-CN', '日志管理', '日志管理菜单'),
  (108,  'zh-TW', '日誌管理', '日誌管理選單'),
  (108,  'en-US', 'Log Management', 'Log management'),
  (115,  'zh-CN', '表单构建', '表单构建菜单'),
  (115,  'zh-TW', '表單建置', '表單建置選單'),
  (115,  'en-US', 'Form Builder', 'Form builder'),
  (117,  'zh-CN', '系统接口', '系统接口菜单'),
  (117,  'zh-TW', '系統介面', '系統介面選單'),
  (117,  'en-US', 'System API', 'System API'),
  (118,  'zh-CN', '权限总览', '权限总览菜单'),
  (118,  'zh-TW', '權限總覽', '權限總覽選單'),
  (118,  'en-US', 'Permission Overview', 'Permission overview'),
  (119,  'zh-CN', '邮件发送', '邮件通知接口权限'),
  (119,  'zh-TW', '郵件發送', '郵件通知介面權限'),
  (119,  'en-US', 'Send Email', 'Email notification permission'),
  (120,  'zh-CN', 'Telegram发送', 'Telegram通知接口权限'),
  (120,  'zh-TW', 'Telegram發送', 'Telegram通知介面權限'),
  (120,  'en-US', 'Send Telegram', 'Telegram notification permission'),
  (121,  'zh-CN', 'WhatsApp发送', 'WhatsApp通知接口权限'),
  (121,  'zh-TW', 'WhatsApp發送', 'WhatsApp通知介面權限'),
  (121,  'en-US', 'Send WhatsApp', 'WhatsApp notification permission'),
  (500,  'zh-CN', '操作日志', '操作日志菜单'),
  (500,  'zh-TW', '操作日誌', '操作日誌選單'),
  (500,  'en-US', 'Operation Logs', 'Operation logs'),
  (501,  'zh-CN', '登录日志', '登录日志菜单'),
  (501,  'zh-TW', '登入日誌', '登入日誌選單'),
  (501,  'en-US', 'Login Logs', 'Login logs')
) AS v(menu_id, locale, menu_name, remark)
WHERE EXISTS (
  SELECT 1 FROM sys_menu m WHERE m.menu_id = v.menu_id
)
ON CONFLICT (menu_id, locale) DO UPDATE
SET menu_name = EXCLUDED.menu_name,
    remark = EXCLUDED.remark,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;
