-- 系统通知页面菜单。
-- 发送按钮权限沿用已有 notification:email:send 和 notification:telegram:send。
-- 本脚本不会自动给普通角色授权，请管理员在角色权限中按需勾选。

CREATE TABLE IF NOT EXISTS sys_menu_i18n (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    locale VARCHAR(20) NOT NULL,
    menu_name VARCHAR(100) NOT NULL,
    remark VARCHAR(500) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_menu_i18n_menu_locale UNIQUE (menu_id, locale),
    CONSTRAINT fk_sys_menu_i18n_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(menu_id) ON DELETE CASCADE
);

INSERT INTO sys_menu (
    menu_id, menu_name, parent_id, order_num, path, component, "query", route_name,
    is_frame, is_cache, menu_type, visible, status, perms, icon, create_by,
    create_time, update_by, update_time, remark
)
SELECT
    122, '系统通知', 1, 9, 'notification', 'notification/index', '', '',
    1, 0, 'C', '0', '0', 'notification:view', 'message', 'admin',
    CURRENT_TIMESTAMP, '', NULL, '邮件和 Telegram 通知发送页面'
WHERE NOT EXISTS (
    SELECT 1 FROM sys_menu WHERE menu_id = 122 OR perms = 'notification:view'
);

INSERT INTO sys_menu_i18n (menu_id, locale, menu_name, remark)
SELECT 122, v.locale, v.menu_name, v.remark
FROM (VALUES
    ('zh-CN', '系统通知', '邮件和 Telegram 通知发送页面'),
    ('zh-TW', '系統通知', '郵件和 Telegram 通知發送頁面'),
    ('en-US', 'System Notifications', 'Send email and Telegram notifications')
) AS v(locale, menu_name, remark)
WHERE EXISTS (SELECT 1 FROM sys_menu WHERE menu_id = 122)
  AND NOT EXISTS (
      SELECT 1 FROM sys_menu_i18n WHERE menu_id = 122 AND locale = v.locale
  );
