-- FiveTech Dashboard PostgreSQL schema
-- PostgreSQL 16+
--
-- This file creates tables, indexes, constraints and data dictionary comments only.
-- It does not insert business data and does not drop existing tables.
-- Execute this file before fivetech_seed_postgresql.sql.

BEGIN;

-- Core tables required by login, organization, RBAC, notifications and audit logs.
CREATE TABLE sys_dept (
  dept_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 200),
  parent_id    BIGINT DEFAULT 0,
  ancestors    VARCHAR(50) DEFAULT '',
  dept_name    VARCHAR(30) DEFAULT '',
  order_num    INTEGER DEFAULT 0,
  leader       VARCHAR(20) DEFAULT NULL,
  phone        VARCHAR(11) DEFAULT NULL,
  email        VARCHAR(50) DEFAULT NULL,
  status       CHAR(1) DEFAULT '0',
  del_flag     CHAR(1) DEFAULT '0',
  create_by    VARCHAR(64) DEFAULT '',
  create_time  TIMESTAMP,
  update_by    VARCHAR(64) DEFAULT '',
  update_time  TIMESTAMP,
  PRIMARY KEY (dept_id)
);
COMMENT ON TABLE sys_dept IS '部门表';
CREATE TABLE sys_user (
  user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dept_id         BIGINT DEFAULT NULL,
  user_name       VARCHAR(30) NOT NULL,
  nick_name       VARCHAR(30) NOT NULL,
  user_type       VARCHAR(2) DEFAULT '00',
  email           VARCHAR(50) DEFAULT '',
  phonenumber     VARCHAR(11) DEFAULT '',
  sex             CHAR(1) DEFAULT '0',
  avatar          VARCHAR(100) DEFAULT '',
  password        VARCHAR(100) DEFAULT '',
  ga_secret       VARCHAR(64) DEFAULT NULL,
  ga_status       INTEGER DEFAULT 0,
  notification_contacts JSONB NOT NULL DEFAULT '{}'::jsonb,
  status          CHAR(1) DEFAULT '0',
  del_flag        CHAR(1) DEFAULT '0',
  login_ip        VARCHAR(128) DEFAULT '',
  login_date      TIMESTAMP,
  pwd_update_date TIMESTAMP,
  create_by       VARCHAR(64) DEFAULT '',
  create_time     TIMESTAMP,
  update_by       VARCHAR(64) DEFAULT '',
  update_time     TIMESTAMP,
  remark          VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE sys_user IS '用户信息表';

-- Database-level uniqueness is required because service-level
-- check-then-insert validation is not safe under concurrent requests.
CREATE UNIQUE INDEX uk_sys_user_user_name_active
  ON sys_user (user_name) WHERE del_flag = '0';
CREATE UNIQUE INDEX uk_sys_user_email_active
  ON sys_user (email) WHERE del_flag = '0' AND email <> '';
CREATE UNIQUE INDEX uk_sys_user_phone_active
  ON sys_user (phonenumber) WHERE del_flag = '0' AND phonenumber <> '';

CREATE TABLE sys_post (
  post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_code   VARCHAR(64) NOT NULL,
  post_name   VARCHAR(50) NOT NULL,
  post_sort   INTEGER NOT NULL,
  status      CHAR(1) NOT NULL,
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (post_id)
);
COMMENT ON TABLE sys_post IS '岗位信息表';
CREATE TABLE sys_role (
  role_id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  role_name           VARCHAR(30) NOT NULL,
  role_key            VARCHAR(100) NOT NULL,
  role_sort           INTEGER NOT NULL,
  data_scope          CHAR(1) DEFAULT '1',
  menu_check_strictly  BOOLEAN DEFAULT TRUE,
  dept_check_strictly  BOOLEAN DEFAULT TRUE,
  status              CHAR(1) NOT NULL,
  del_flag            CHAR(1) DEFAULT '0',
  create_by           VARCHAR(64) DEFAULT '',
  create_time         TIMESTAMP,
  update_by           VARCHAR(64) DEFAULT '',
  update_time         TIMESTAMP,
  remark              VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (role_id)
);
COMMENT ON TABLE sys_role IS '角色信息表';

CREATE UNIQUE INDEX uk_sys_role_name_active
  ON sys_role (role_name) WHERE del_flag = '0';
CREATE UNIQUE INDEX uk_sys_role_key_active
  ON sys_role (role_key) WHERE del_flag = '0';

CREATE TABLE sys_menu (
  menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000),
  menu_name   VARCHAR(50) NOT NULL,
  parent_id   BIGINT DEFAULT 0,
  order_num   INTEGER DEFAULT 0,
  path        VARCHAR(200) DEFAULT '',
  component   VARCHAR(255) DEFAULT NULL,
  query       VARCHAR(255) DEFAULT NULL,
  route_name  VARCHAR(50) DEFAULT '',
  is_frame    INTEGER DEFAULT 1,
  is_cache    INTEGER DEFAULT 0,
  menu_type   CHAR(1) DEFAULT '',
  visible     CHAR(1) DEFAULT '0',


  status      CHAR(1) DEFAULT '0',
  perms       VARCHAR(100) DEFAULT NULL,
  icon        VARCHAR(100) DEFAULT '#',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT '',
  PRIMARY KEY (menu_id)
);
COMMENT ON TABLE sys_menu IS '菜单权限表';
CREATE TABLE sys_menu_i18n (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  menu_id     BIGINT NOT NULL,
  locale      VARCHAR(20) NOT NULL,
  menu_name   VARCHAR(100) NOT NULL,
  remark      VARCHAR(500) DEFAULT '',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_sys_menu_i18n_menu_locale UNIQUE (menu_id, locale),
  CONSTRAINT fk_sys_menu_i18n_menu FOREIGN KEY (menu_id)
    REFERENCES sys_menu(menu_id) ON DELETE CASCADE
);
COMMENT ON TABLE sys_menu_i18n IS '菜单多语言名称表：支持 zh-CN、zh-TW 和 en-US 菜单展示';

CREATE TABLE sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户和角色关联表';
CREATE TABLE sys_role_menu (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);
COMMENT ON TABLE sys_role_menu IS '角色和菜单关联表';
CREATE TABLE sys_role_dept (
  role_id BIGINT NOT NULL,
  dept_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, dept_id)
);
COMMENT ON TABLE sys_role_dept IS '角色和部门关联表';
CREATE TABLE sys_user_post (
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, post_id)
);
COMMENT ON TABLE sys_user_post IS '用户与岗位关联表';
CREATE TABLE sys_oper_log (
  oper_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  title          VARCHAR(50) DEFAULT '',
  business_type  INTEGER DEFAULT 0,
  method         VARCHAR(200) DEFAULT '',
  request_method VARCHAR(10) DEFAULT '',
  operator_type  INTEGER DEFAULT 0,
  oper_name      VARCHAR(50) DEFAULT '',
  dept_name      VARCHAR(50) DEFAULT '',
  oper_url       VARCHAR(255) DEFAULT '',
  oper_ip        VARCHAR(128) DEFAULT '',
  oper_location  VARCHAR(255) DEFAULT '',
  oper_param     VARCHAR(2000) DEFAULT '',
  json_result    VARCHAR(2000) DEFAULT '',
  status         INTEGER DEFAULT 0,
  error_msg      VARCHAR(2000) DEFAULT '',
  oper_time      TIMESTAMP,
  cost_time      BIGINT DEFAULT 0,
  PRIMARY KEY (oper_id)
);
COMMENT ON TABLE sys_oper_log IS '操作日志记录';
CREATE INDEX idx_sys_oper_log_bt ON sys_oper_log (business_type);
CREATE INDEX idx_sys_oper_log_s  ON sys_oper_log (status);
CREATE INDEX idx_sys_oper_log_ot ON sys_oper_log (oper_time);
CREATE TABLE sys_dict_type (
  dict_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dict_name   VARCHAR(100) DEFAULT '',
  dict_type   VARCHAR(100) DEFAULT '',
  status      CHAR(1) DEFAULT '0',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (dict_id),
  UNIQUE (dict_type)
);
COMMENT ON TABLE sys_dict_type IS '字典类型表';

CREATE TABLE sys_dict_data (
  dict_code   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dict_sort   INTEGER DEFAULT 0,
  dict_label  VARCHAR(100) DEFAULT '',
  dict_value  VARCHAR(100) DEFAULT '',
  dict_type   VARCHAR(100) DEFAULT '',
  css_class   VARCHAR(100) DEFAULT NULL,
  list_class  VARCHAR(100) DEFAULT NULL,
  is_default  CHAR(1) DEFAULT 'N',
  status      CHAR(1) DEFAULT '0',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (dict_code)
);
COMMENT ON TABLE sys_dict_data IS '字典数据表';

CREATE TABLE sys_config (
  config_id    INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  config_name  VARCHAR(100) DEFAULT '',
  config_key   VARCHAR(100) DEFAULT '',
  config_value VARCHAR(500) DEFAULT '',
  config_type  CHAR(1) DEFAULT 'N',
  create_by    VARCHAR(64) DEFAULT '',
  create_time  TIMESTAMP,
  update_by    VARCHAR(64) DEFAULT '',
  update_time  TIMESTAMP,
  remark       VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (config_id)
);
COMMENT ON TABLE sys_config IS '参数配置表';

CREATE TABLE sys_logininfor (
  info_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  user_name      VARCHAR(50) DEFAULT '',
  ipaddr         VARCHAR(128) DEFAULT '',
  login_location VARCHAR(255) DEFAULT '',
  browser        VARCHAR(50) DEFAULT '',
  os             VARCHAR(50) DEFAULT '',
  status         CHAR(1) DEFAULT '0',
  msg            VARCHAR(255) DEFAULT '',
  login_time     TIMESTAMP,
  PRIMARY KEY (info_id)
);
COMMENT ON TABLE sys_logininfor IS '系统访问记录';
CREATE INDEX idx_sys_logininfor_s  ON sys_logininfor (status);
CREATE INDEX idx_sys_logininfor_lt ON sys_logininfor (login_time);

-- 15. 定时任务调度表
CREATE TABLE sys_job (
  job_id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  job_name        VARCHAR(64) DEFAULT '',
  job_group       VARCHAR(64) DEFAULT 'DEFAULT',
  invoke_target   VARCHAR(500) NOT NULL,
  cron_expression VARCHAR(255) DEFAULT '',
  misfire_policy  VARCHAR(20) DEFAULT '3',
  concurrent      CHAR(1) DEFAULT '1',
  status          CHAR(1) DEFAULT '0',
  create_by       VARCHAR(64) DEFAULT '',
  create_time     TIMESTAMP,
  update_by       VARCHAR(64) DEFAULT '',
  update_time     TIMESTAMP,
  remark          VARCHAR(500) DEFAULT '',
  PRIMARY KEY (job_id, job_name, job_group)
);
COMMENT ON TABLE sys_job IS '定时任务调度表';

-- 16. 定时任务调度日志表
CREATE TABLE sys_job_log (
  job_log_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  job_name       VARCHAR(64) NOT NULL,
  job_group      VARCHAR(64) NOT NULL,
  invoke_target  VARCHAR(500) NOT NULL,
  job_message    VARCHAR(500),
  status         CHAR(1) DEFAULT '0',
  exception_info VARCHAR(2000) DEFAULT '',
  start_time     TIMESTAMP,
  end_time       TIMESTAMP,
  create_time    TIMESTAMP,
  PRIMARY KEY (job_log_id)
);
COMMENT ON TABLE sys_job_log IS '定时任务调度日志表';

-- Foreign keys for relationship integrity.
ALTER TABLE sys_user
  ADD CONSTRAINT fk_sys_user_dept
  FOREIGN KEY (dept_id) REFERENCES sys_dept(dept_id) ON DELETE SET NULL;

ALTER TABLE sys_user_role
  ADD CONSTRAINT fk_sys_user_role_user
  FOREIGN KEY (user_id) REFERENCES sys_user(user_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sys_user_role_role
  FOREIGN KEY (role_id) REFERENCES sys_role(role_id) ON DELETE CASCADE;

ALTER TABLE sys_role_menu
  ADD CONSTRAINT fk_sys_role_menu_role
  FOREIGN KEY (role_id) REFERENCES sys_role(role_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sys_role_menu_menu
  FOREIGN KEY (menu_id) REFERENCES sys_menu(menu_id) ON DELETE CASCADE;

ALTER TABLE sys_role_dept
  ADD CONSTRAINT fk_sys_role_dept_role
  FOREIGN KEY (role_id) REFERENCES sys_role(role_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sys_role_dept_dept
  FOREIGN KEY (dept_id) REFERENCES sys_dept(dept_id) ON DELETE CASCADE;

ALTER TABLE sys_user_post
  ADD CONSTRAINT fk_sys_user_post_user
  FOREIGN KEY (user_id) REFERENCES sys_user(user_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sys_user_post_post
  FOREIGN KEY (post_id) REFERENCES sys_post(post_id) ON DELETE CASCADE;

-- Domain checks for security-sensitive status fields.
ALTER TABLE sys_user
  ADD CONSTRAINT ck_sys_user_type CHECK (user_type IN ('00', '01')),
  ADD CONSTRAINT ck_sys_user_ga_status CHECK (ga_status IN (0, 1, 2));

ALTER TABLE sys_role
  ADD CONSTRAINT ck_sys_role_data_scope CHECK (data_scope IN ('1', '2', '3', '4', '5'));

-- Table descriptions.
COMMENT ON TABLE sys_dept IS '组织和部门表：保存组织树、部门层级、负责人及部门联系方式。';
COMMENT ON TABLE sys_user IS '用户表：保存登录账号、密码哈希、用户类型、组织归属、TOTP状态及通知联系人。';
COMMENT ON TABLE sys_post IS '岗位表：保存岗位信息，仅用于用户岗位归类，不替代RBAC权限。';
COMMENT ON TABLE sys_role IS '角色表：保存RBAC角色及Data Scope数据范围。';
COMMENT ON TABLE sys_menu IS '菜单权限表：保存目录、页面和按钮权限，perms对应后端权限标识。';
COMMENT ON TABLE sys_menu_i18n IS '菜单多语言表：保存简体中文、繁体中文和英文菜单名称。';
COMMENT ON TABLE sys_user_role IS '用户角色关联表：建立用户与角色的多对多关系。';
COMMENT ON TABLE sys_role_menu IS '角色菜单权限关联表：建立角色与菜单及按钮权限的多对多关系。';
COMMENT ON TABLE sys_role_dept IS '角色部门数据范围表：保存角色可访问的部门范围。';
COMMENT ON TABLE sys_user_post IS '用户岗位关联表：建立用户与岗位的多对多关系。';
COMMENT ON TABLE sys_oper_log IS '操作日志表：记录用户、组织、角色、权限和通知等管理操作。';
COMMENT ON TABLE sys_logininfor IS '登录日志表：记录登录成功、失败、退出及异常登录信息。';
COMMENT ON TABLE sys_config IS '系统参数表：保存登录黑名单、初始密码和密码策略等运行参数。';
COMMENT ON TABLE sys_dict_type IS '字典类型表：保存系统状态和页面展示所需的字典分类。';
COMMENT ON TABLE sys_dict_data IS '字典数据表：保存字典分类下的具体键值和展示标签。';
COMMENT ON TABLE sys_job IS '兼容保留的定时任务表：当前未开放对应菜单，删除前需先移除后端任务模块依赖。';
COMMENT ON TABLE sys_job_log IS '兼容保留的定时任务日志表：与sys_job配套使用。';

-- sys_dept columns.
COMMENT ON COLUMN sys_dept.dept_id IS '部门主键ID';
COMMENT ON COLUMN sys_dept.parent_id IS '父部门ID，根部门为0';
COMMENT ON COLUMN sys_dept.ancestors IS '祖先部门ID路径，例如0,100,101';
COMMENT ON COLUMN sys_dept.dept_name IS '部门名称';
COMMENT ON COLUMN sys_dept.order_num IS '同级部门显示顺序';
COMMENT ON COLUMN sys_dept.leader IS '部门负责人账号或姓名';
COMMENT ON COLUMN sys_dept.phone IS '部门联系电话，仅用于通知或展示';
COMMENT ON COLUMN sys_dept.email IS '部门通知邮箱，仅用于通知或展示';
COMMENT ON COLUMN sys_dept.status IS '部门状态：0正常，1停用';
COMMENT ON COLUMN sys_dept.del_flag IS '删除标志：0存在，2删除';
COMMENT ON COLUMN sys_dept.create_by IS '创建人';
COMMENT ON COLUMN sys_dept.create_time IS '创建时间';
COMMENT ON COLUMN sys_dept.update_by IS '最后修改人';
COMMENT ON COLUMN sys_dept.update_time IS '最后修改时间';

-- sys_user columns.
COMMENT ON COLUMN sys_user.user_id IS '用户主键ID';
COMMENT ON COLUMN sys_user.dept_id IS '所属部门ID';
COMMENT ON COLUMN sys_user.user_name IS '登录账号';
COMMENT ON COLUMN sys_user.nick_name IS '用户昵称';
COMMENT ON COLUMN sys_user.user_type IS '用户类型：00普通用户，01超级管理员';
COMMENT ON COLUMN sys_user.email IS '用户邮箱，可作为邮件通知地址';
COMMENT ON COLUMN sys_user.phonenumber IS '用户手机号，可作为外部通知地址';
COMMENT ON COLUMN sys_user.sex IS '性别编码';
COMMENT ON COLUMN sys_user.avatar IS '头像路径或地址';
COMMENT ON COLUMN sys_user.password IS '密码哈希，禁止保存明文密码';
COMMENT ON COLUMN sys_user.ga_secret IS 'Google Authenticator TOTP密钥，生产环境应加密存储';
COMMENT ON COLUMN sys_user.ga_status IS 'TOTP状态：0未开通，1待绑定，2已绑定';
COMMENT ON COLUMN sys_user.notification_contacts IS 'Telegram、WhatsApp、Lark等通知联系人JSONB信息';
COMMENT ON COLUMN sys_user.status IS '账号状态：0正常，1停用';
COMMENT ON COLUMN sys_user.del_flag IS '删除标志：0存在，2删除';
COMMENT ON COLUMN sys_user.login_ip IS '最后登录IP';
COMMENT ON COLUMN sys_user.login_date IS '最后登录时间';
COMMENT ON COLUMN sys_user.pwd_update_date IS '最后修改密码时间';
COMMENT ON COLUMN sys_user.create_by IS '创建人';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';
COMMENT ON COLUMN sys_user.update_by IS '最后修改人';
COMMENT ON COLUMN sys_user.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_user.remark IS '备注';

-- sys_role columns.
COMMENT ON COLUMN sys_role.role_id IS '角色主键ID';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.role_key IS '角色标识，超级管理员使用admin';
COMMENT ON COLUMN sys_role.role_sort IS '角色显示顺序';
COMMENT ON COLUMN sys_role.data_scope IS '数据范围：1全部，2自定义，3本部门，4本部门及下级，5仅本人';
COMMENT ON COLUMN sys_role.menu_check_strictly IS '菜单树父子节点是否严格关联';
COMMENT ON COLUMN sys_role.dept_check_strictly IS '部门树父子节点是否严格关联';
COMMENT ON COLUMN sys_role.status IS '角色状态：0正常，1停用';
COMMENT ON COLUMN sys_role.del_flag IS '删除标志：0存在，2删除';
COMMENT ON COLUMN sys_role.create_by IS '创建人';
COMMENT ON COLUMN sys_role.create_time IS '创建时间';
COMMENT ON COLUMN sys_role.update_by IS '最后修改人';
COMMENT ON COLUMN sys_role.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_role.remark IS '备注';

-- sys_menu columns.
COMMENT ON COLUMN sys_menu.menu_id IS '菜单或权限主键ID';
COMMENT ON COLUMN sys_menu.menu_name IS '菜单或权限名称';
COMMENT ON COLUMN sys_menu.parent_id IS '父菜单ID，根菜单为0';
COMMENT ON COLUMN sys_menu.order_num IS '显示顺序';
COMMENT ON COLUMN sys_menu.path IS '前端路由路径';
COMMENT ON COLUMN sys_menu.component IS '前端组件路径';
COMMENT ON COLUMN sys_menu.query IS '路由查询参数';
COMMENT ON COLUMN sys_menu.route_name IS '路由名称';
COMMENT ON COLUMN sys_menu.is_frame IS '是否外链：1否，0是';
COMMENT ON COLUMN sys_menu.is_cache IS '是否缓存：0否，1是';
COMMENT ON COLUMN sys_menu.menu_type IS '菜单类型：M目录，C菜单，F按钮';
COMMENT ON COLUMN sys_menu.visible IS '菜单可见性：0显示，1隐藏';
COMMENT ON COLUMN sys_menu.status IS '菜单状态：0正常，1停用';
COMMENT ON COLUMN sys_menu.perms IS '后端权限标识，例如system:user:list';
COMMENT ON COLUMN sys_menu.icon IS '菜单图标';
COMMENT ON COLUMN sys_menu.create_by IS '创建人';
COMMENT ON COLUMN sys_menu.create_time IS '创建时间';
COMMENT ON COLUMN sys_menu.update_by IS '最后修改人';
COMMENT ON COLUMN sys_menu.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_menu.remark IS '备注';

-- Relationship and audit columns.
COMMENT ON COLUMN sys_menu_i18n.menu_id IS '关联sys_menu.menu_id';
COMMENT ON COLUMN sys_menu_i18n.locale IS '语言代码：zh-CN、zh-TW、en-US';
COMMENT ON COLUMN sys_menu_i18n.menu_name IS '对应语言的菜单名称';
COMMENT ON COLUMN sys_menu_i18n.remark IS '对应语言的菜单说明';
COMMENT ON COLUMN sys_user_role.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_role.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单或按钮权限ID';
COMMENT ON COLUMN sys_role_dept.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_dept.dept_id IS '部门ID';
COMMENT ON COLUMN sys_user_post.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_post.post_id IS '岗位ID';

-- Compatibility table field comments.
COMMENT ON COLUMN sys_post.post_id IS '岗位主键ID';
COMMENT ON COLUMN sys_post.post_code IS '岗位编码';
COMMENT ON COLUMN sys_post.post_name IS '岗位名称';
COMMENT ON COLUMN sys_post.post_sort IS '岗位显示顺序';
COMMENT ON COLUMN sys_post.status IS '岗位状态：0正常，1停用';
COMMENT ON COLUMN sys_oper_log.oper_id IS '操作日志主键ID';
COMMENT ON COLUMN sys_oper_log.title IS '业务模块名称';
COMMENT ON COLUMN sys_oper_log.business_type IS '业务操作类型';
COMMENT ON COLUMN sys_oper_log.method IS 'Java方法名称';
COMMENT ON COLUMN sys_oper_log.request_method IS 'HTTP请求方法';
COMMENT ON COLUMN sys_oper_log.operator_type IS '操作人类型';
COMMENT ON COLUMN sys_oper_log.oper_name IS '操作账号';
COMMENT ON COLUMN sys_oper_log.dept_name IS '操作人部门';
COMMENT ON COLUMN sys_oper_log.oper_url IS '请求URL';
COMMENT ON COLUMN sys_oper_log.oper_ip IS '操作IP';
COMMENT ON COLUMN sys_oper_log.oper_location IS '操作地点';
COMMENT ON COLUMN sys_oper_log.oper_param IS '请求参数，禁止记录密码和密钥';
COMMENT ON COLUMN sys_oper_log.json_result IS '响应结果摘要';
COMMENT ON COLUMN sys_oper_log.status IS '操作结果：0成功，1失败';
COMMENT ON COLUMN sys_oper_log.error_msg IS '错误信息';
COMMENT ON COLUMN sys_oper_log.oper_time IS '操作时间';
COMMENT ON COLUMN sys_oper_log.cost_time IS '耗时毫秒数';
COMMENT ON COLUMN sys_logininfor.info_id IS '登录日志主键ID';
COMMENT ON COLUMN sys_logininfor.user_name IS '登录账号';
COMMENT ON COLUMN sys_logininfor.ipaddr IS '登录IP';
COMMENT ON COLUMN sys_logininfor.login_location IS '登录地点';
COMMENT ON COLUMN sys_logininfor.browser IS '浏览器';
COMMENT ON COLUMN sys_logininfor.os IS '操作系统';
COMMENT ON COLUMN sys_logininfor.status IS '登录结果：0成功，1失败';
COMMENT ON COLUMN sys_logininfor.msg IS '登录结果说明';
COMMENT ON COLUMN sys_logininfor.login_time IS '登录时间';

-- Remaining compatibility table fields.
COMMENT ON COLUMN sys_post.create_by IS '创建人';
COMMENT ON COLUMN sys_post.create_time IS '创建时间';
COMMENT ON COLUMN sys_post.update_by IS '最后修改人';
COMMENT ON COLUMN sys_post.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_post.remark IS '备注';
COMMENT ON COLUMN sys_dict_type.dict_id IS '字典类型主键ID';
COMMENT ON COLUMN sys_dict_type.dict_name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.dict_type IS '字典类型编码';
COMMENT ON COLUMN sys_dict_type.status IS '字典状态：0正常，1停用';
COMMENT ON COLUMN sys_dict_data.dict_code IS '字典数据主键ID';
COMMENT ON COLUMN sys_dict_data.dict_sort IS '字典排序';
COMMENT ON COLUMN sys_dict_data.dict_label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.dict_value IS '字典值';
COMMENT ON COLUMN sys_dict_data.dict_type IS '所属字典类型编码';
COMMENT ON COLUMN sys_dict_data.status IS '字典数据状态：0正常，1停用';
COMMENT ON COLUMN sys_config.config_id IS '配置主键ID';
COMMENT ON COLUMN sys_config.config_name IS '配置名称';
COMMENT ON COLUMN sys_config.config_key IS '配置键';
COMMENT ON COLUMN sys_config.config_value IS '配置值';
COMMENT ON COLUMN sys_config.config_type IS '配置类型：Y系统内置，N普通配置';
COMMENT ON COLUMN sys_job.job_id IS '任务主键ID';
COMMENT ON COLUMN sys_job.job_name IS '任务名称';
COMMENT ON COLUMN sys_job.invoke_target IS '任务调用目标';
COMMENT ON COLUMN sys_job.cron_expression IS 'Cron表达式';
COMMENT ON COLUMN sys_job.status IS '任务状态';
COMMENT ON COLUMN sys_job_log.job_log_id IS '任务日志主键ID';
COMMENT ON COLUMN sys_job_log.job_name IS '任务名称';
COMMENT ON COLUMN sys_job_log.status IS '任务执行状态';
COMMENT ON COLUMN sys_job_log.exception_info IS '异常信息';
COMMENT ON COLUMN sys_job_log.start_time IS '开始时间';
COMMENT ON COLUMN sys_job_log.end_time IS '结束时间';
COMMENT ON COLUMN sys_post.post_code IS '岗位编码';
COMMENT ON COLUMN sys_post.post_name IS '岗位名称';
COMMENT ON COLUMN sys_post.post_sort IS '岗位显示顺序';
COMMENT ON COLUMN sys_post.status IS '岗位状态：0正常，1停用';
COMMENT ON COLUMN sys_dict_type.create_by IS '创建人';
COMMENT ON COLUMN sys_dict_type.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict_type.update_by IS '最后修改人';
COMMENT ON COLUMN sys_dict_type.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_dict_type.remark IS '备注';
COMMENT ON COLUMN sys_dict_data.css_class IS '标签CSS样式';
COMMENT ON COLUMN sys_dict_data.list_class IS '列表展示样式';
COMMENT ON COLUMN sys_dict_data.is_default IS '是否默认值：Y是，N否';
COMMENT ON COLUMN sys_dict_data.create_by IS '创建人';
COMMENT ON COLUMN sys_dict_data.create_time IS '创建时间';
COMMENT ON COLUMN sys_dict_data.update_by IS '最后修改人';
COMMENT ON COLUMN sys_dict_data.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_dict_data.remark IS '备注';
COMMENT ON COLUMN sys_config.create_by IS '创建人';
COMMENT ON COLUMN sys_config.create_time IS '创建时间';
COMMENT ON COLUMN sys_config.update_by IS '最后修改人';
COMMENT ON COLUMN sys_config.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_config.remark IS '备注';
COMMENT ON COLUMN sys_job.job_group IS '任务分组';
COMMENT ON COLUMN sys_job.misfire_policy IS '错过触发策略';
COMMENT ON COLUMN sys_job.concurrent IS '是否允许并发执行';
COMMENT ON COLUMN sys_job.create_by IS '创建人';
COMMENT ON COLUMN sys_job.create_time IS '创建时间';
COMMENT ON COLUMN sys_job.update_by IS '最后修改人';
COMMENT ON COLUMN sys_job.update_time IS '最后修改时间';
COMMENT ON COLUMN sys_job.remark IS '备注';
COMMENT ON COLUMN sys_job_log.job_group IS '任务分组';
COMMENT ON COLUMN sys_job_log.invoke_target IS '任务调用目标';
COMMENT ON COLUMN sys_job_log.job_message IS '执行消息';
COMMENT ON COLUMN sys_job_log.exception_info IS '异常信息';
COMMENT ON COLUMN sys_job_log.create_time IS '创建时间';
COMMENT ON COLUMN sys_menu_i18n.id IS '多语言记录主键ID';
COMMENT ON COLUMN sys_menu_i18n.created_at IS '创建时间';
COMMENT ON COLUMN sys_menu_i18n.updated_at IS '最后修改时间';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单或按钮权限ID';
COMMENT ON COLUMN sys_role_dept.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_dept.dept_id IS '部门ID';
COMMENT ON COLUMN sys_user_post.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_post.post_id IS '岗位ID';
COMMIT;
