-- FiveTech Dashboard PostgreSQL 16+ final initialization script
-- Standalone script: execute this file directly with psql.

DROP TABLE IF EXISTS sys_job_log;
DROP TABLE IF EXISTS sys_job;
DROP TABLE IF EXISTS sys_logininfor;
DROP TABLE IF EXISTS sys_config;
DROP TABLE IF EXISTS sys_dict_data;
DROP TABLE IF EXISTS sys_dict_type;
DROP TABLE IF EXISTS sys_oper_log;
DROP TABLE IF EXISTS sys_user_post;
DROP TABLE IF EXISTS sys_role_dept;
DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_menu_i18n;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS sys_post;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS sys_dept;

-- 1. 部门表
CREATE TABLE sys_dept (
  dept_id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 200),
  parent_id    BIGINT DEFAULT 0,
  ancestors    VARCHAR(50) DEFAULT '',
  dept_name    VARCHAR(30) DEFAULT '',
  order_num    INTEGER DEFAULT 0,
  leader       VARCHAR(20) DEFAULT NULL,
  phone        VARCHAR(11) DEFAULT NULL,
  email        VARCHAR(50) DEFAULT NULL,
  status       CHAR(1) DEFAULT '0',
  del_flag     CHAR(1) DEFAULT '0',
  create_by    VARCHAR(64) DEFAULT '',
  create_time  TIMESTAMP,
  update_by    VARCHAR(64) DEFAULT '',
  update_time  TIMESTAMP,
  PRIMARY KEY (dept_id)
);
COMMENT ON TABLE sys_dept IS '部门表';

INSERT INTO sys_dept VALUES
  (100, 0,   '0',         'FiveTech',   0, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (101, 100, '0,100',     'Head Office', 1, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (102, 100, '0,100',     'Business Unit', 2, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (103, 101, '0,100,101', 'Engineering', 1, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (104, 101, '0,100,101', 'Marketing',   2, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (105, 101, '0,100,101', 'QA',          3, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (106, 101, '0,100,101', 'Finance',     4, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (107, 101, '0,100,101', 'Operations',  5, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (108, 102, '0,100,102', 'Marketing',   1, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL),
  (109, 102, '0,100,102', 'Finance',     2, 'admin', '', '', '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL);

-- 2. 用户信息表
CREATE TABLE sys_user (
  user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dept_id         BIGINT DEFAULT NULL,
  user_name       VARCHAR(30) NOT NULL,
  nick_name       VARCHAR(30) NOT NULL,
  user_type       VARCHAR(2) DEFAULT '00',
  email           VARCHAR(50) DEFAULT '',
  phonenumber     VARCHAR(11) DEFAULT '',
  sex             CHAR(1) DEFAULT '0',
  avatar          VARCHAR(100) DEFAULT '',
  password        VARCHAR(100) DEFAULT '',
  ga_secret       VARCHAR(64) DEFAULT NULL,
  ga_status       INTEGER DEFAULT 0,
  notification_contacts JSONB NOT NULL DEFAULT '{}'::jsonb,
  status          CHAR(1) DEFAULT '0',
  del_flag        CHAR(1) DEFAULT '0',
  login_ip        VARCHAR(128) DEFAULT '',
  login_date      TIMESTAMP,
  pwd_update_date TIMESTAMP,
  create_by       VARCHAR(64) DEFAULT '',
  create_time     TIMESTAMP,
  update_by       VARCHAR(64) DEFAULT '',
  update_time     TIMESTAMP,
  remark          VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE sys_user IS '用户信息表';

-- Database-level uniqueness is required because service-level
-- check-then-insert validation is not safe under concurrent requests.
CREATE UNIQUE INDEX uk_sys_user_user_name_active
  ON sys_user (user_name) WHERE del_flag = '0';
CREATE UNIQUE INDEX uk_sys_user_email_active
  ON sys_user (email) WHERE del_flag = '0' AND email <> '';
CREATE UNIQUE INDEX uk_sys_user_phone_active
  ON sys_user (phonenumber) WHERE del_flag = '0' AND phonenumber <> '';

INSERT INTO sys_user VALUES
  (1, 103, 'admin', 'System Administrator', '01', '', '', '0', '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', NULL, '0', '{}'::jsonb, '0', '0', '', NULL, NULL, 'admin', CURRENT_TIMESTAMP, '', NULL, 'Super administrator; change the initial password immediately'),
  (2, 105, 'ry',    'Test User',            '00', '', '', '0', '', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', NULL, '0', '{}'::jsonb, '0', '0', '', NULL, NULL, 'admin', CURRENT_TIMESTAMP, '', NULL, 'Test user');

-- 3. 岗位信息表
CREATE TABLE sys_post (
  post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  post_code   VARCHAR(64) NOT NULL,
  post_name   VARCHAR(50) NOT NULL,
  post_sort   INTEGER NOT NULL,
  status      CHAR(1) NOT NULL,
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (post_id)
);
COMMENT ON TABLE sys_post IS '岗位信息表';

INSERT INTO sys_post VALUES
  (1, 'ceo',  '董事长',   1, '0', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
  (2, 'se',   '项目经理', 2, '0', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
  (3, 'hr',   '人力资源', 3, '0', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
  (4, 'user', '普通员工', 4, '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '');

-- 4. 角色信息表
CREATE TABLE sys_role (
  role_id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  role_name           VARCHAR(30) NOT NULL,
  role_key            VARCHAR(100) NOT NULL,
  role_sort           INTEGER NOT NULL,
  data_scope          CHAR(1) DEFAULT '1',
  menu_check_strictly  BOOLEAN DEFAULT TRUE,
  dept_check_strictly  BOOLEAN DEFAULT TRUE,
  status              CHAR(1) NOT NULL,
  del_flag            CHAR(1) DEFAULT '0',
  create_by           VARCHAR(64) DEFAULT '',
  create_time         TIMESTAMP,
  update_by           VARCHAR(64) DEFAULT '',
  update_time         TIMESTAMP,
  remark              VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (role_id)
);
COMMENT ON TABLE sys_role IS '角色信息表';

CREATE UNIQUE INDEX uk_sys_role_name_active
  ON sys_role (role_name) WHERE del_flag = '0';
CREATE UNIQUE INDEX uk_sys_role_key_active
  ON sys_role (role_key) WHERE del_flag = '0';

INSERT INTO sys_role VALUES
  (1, '超级管理员', 'admin',  1, '1', TRUE, TRUE, '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '超级管理员'),
  (2, '普通角色',   'common', 2, '2', TRUE, TRUE, '0', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '普通角色');

-- 5. 菜单权限表
CREATE TABLE sys_menu (
  menu_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000),
  menu_name   VARCHAR(50) NOT NULL,
  parent_id   BIGINT DEFAULT 0,
  order_num   INTEGER DEFAULT 0,
  path        VARCHAR(200) DEFAULT '',
  component   VARCHAR(255) DEFAULT NULL,
  query       VARCHAR(255) DEFAULT NULL,
  route_name  VARCHAR(50) DEFAULT '',
  is_frame    INTEGER DEFAULT 1,
  is_cache    INTEGER DEFAULT 0,
  menu_type   CHAR(1) DEFAULT '',
  visible     CHAR(1) DEFAULT '0',


  status      CHAR(1) DEFAULT '0',
  perms       VARCHAR(100) DEFAULT NULL,
  icon        VARCHAR(100) DEFAULT '#',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT '',
  PRIMARY KEY (menu_id)
);
COMMENT ON TABLE sys_menu IS '菜单权限表';

INSERT INTO sys_menu VALUES
('1', '系统管理', '0', '1', 'system',           NULL, '', '', 1, 0, 'M', '0', '0', '', 'system',   'admin', CURRENT_TIMESTAMP, '', NULL, '系统管理目录'),
('2', '系统监控', '0', '2', 'monitor',          NULL, '', '', 1, 0, 'M', '0', '0', '', 'monitor',  'admin', CURRENT_TIMESTAMP, '', NULL, '系统监控目录'),
('3', '系统工具', '0', '3', 'tool',             NULL, '', '', 1, 0, 'M', '0', '0', '', 'tool',     'admin', CURRENT_TIMESTAMP, '', NULL, '系统工具目录'),
('100',  '用户管理', '1',   '1', 'user',       'system/user/index',        '', '', 1, 0, 'C', '0', '0', 'system:user:list',        'user',          'admin', CURRENT_TIMESTAMP, '', NULL, '用户管理菜单'),
('101',  '角色管理', '1',   '2', 'role',       'system/role/index',        '', '', 1, 0, 'C', '0', '0', 'system:role:list',        'peoples',       'admin', CURRENT_TIMESTAMP, '', NULL, '角色管理菜单'),
('102',  '权限管理', '1',   '3', 'menu',       'system/menu/index',        '', '', 1, 0, 'C', '0', '0', 'system:menu:list',        'tree-table',    'admin', CURRENT_TIMESTAMP, '', NULL, '权限管理菜单'),
('103',  '部门管理', '1',   '4', 'dept',       'system/dept/index',        '', '', 1, 0, 'C', '0', '0', 'system:dept:list',        'tree',          'admin', CURRENT_TIMESTAMP, '', NULL, '部门管理菜单'),
('108',  '日志管理', '1',   '8', 'log',        '',                         '', '', 1, 0, 'M', '0', '0', '',                        'log',           'admin', CURRENT_TIMESTAMP, '', NULL, '日志管理菜单'),
('115',  '表单构建', '3',   '1', 'build',      'tool/build/index',         '', '', 1, 0, 'C', '0', '0', 'tool:build:list',         'build',         'admin', CURRENT_TIMESTAMP, '', NULL, '表单构建菜单'),
('117',  '系统接口', '3',   '3', 'swagger',    'tool/swagger/index',       '', '', 1, 0, 'C', '0', '0', 'tool:swagger:list',       'swagger',       'admin', CURRENT_TIMESTAMP, '', NULL, '系统接口菜单'),
('118',  '权限总览',   '1',   '8', 'permission', 'system/permission/index',  '', '', 1, 0, 'C', '0', '0', 'system:permission:view',  'lock',          'admin', CURRENT_TIMESTAMP, '', NULL, '权限总览菜单'),
('119',  '邮件发送',   '1',   '9', '',           '',                         '', '', 1, 0, 'F', '1', '0', 'notification:email:send', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, '邮件通知接口权限'),
('500',  '操作日志', '108', '1', 'operlog',    'monitor/operlog/index',    '', '', 1, 0, 'C', '0', '0', 'monitor:operlog:list',    'form',          'admin', CURRENT_TIMESTAMP, '', NULL, '操作日志菜单'),
('501',  '登录日志', '108', '2', 'logininfor', 'monitor/logininfor/index', '', '', 1, 0, 'C', '0', '0', 'monitor:logininfor:list', 'logininfor',    'admin', CURRENT_TIMESTAMP, '', NULL, '登录日志菜单'),
('1000', '用户查询', '100', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1001', '用户新增', '100', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1002', '用户修改', '100', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1003', '用户删除', '100', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1004', '用户导出', '100', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:export',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1005', '用户导入', '100', '6',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:import',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1006', '重置密码', '100', '7',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd',       '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1007', '角色查询', '101', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1008', '角色新增', '101', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1009', '角色修改', '101', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1010', '角色删除', '101', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1011', '角色导出', '101', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:role:export',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1012', '菜单查询', '102', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1013', '菜单新增', '102', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1014', '菜单修改', '102', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1015', '菜单删除', '102', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1016', '部门查询', '103', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1017', '部门新增', '103', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1018', '部门修改', '103', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1019', '部门删除', '103', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1020', '岗位查询', '104', '1',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1021', '岗位新增', '104', '2',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1022', '岗位修改', '104', '3',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1023', '岗位删除', '104', '4',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1024', '岗位导出', '104', '5',  '', '', '', '', 1, 0, 'F', '0', '0', 'system:post:export',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1025', '字典查询', '105', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1026', '字典新增', '105', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1027', '字典修改', '105', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1028', '字典删除', '105', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1029', '字典导出', '105', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:dict:export',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1030', '参数查询', '106', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:query',        '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1031', '参数新增', '106', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:add',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1032', '参数修改', '106', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:edit',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1033', '参数删除', '106', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:remove',       '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1034', '参数导出', '106', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'system:config:export',       '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1035', '操作查询', '500', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:query',      '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1036', '操作删除', '500', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:remove',     '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1037', '日志导出', '500', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:operlog:export',     '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1038', '登录查询', '501', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:query',   '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1039', '登录删除', '501', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:remove',  '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1040', '日志导出', '501', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:export',  '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1041', '账户解锁', '501', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:logininfor:unlock',  '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1042', '在线查询', '109', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query',       '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1043', '批量强退', '109', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1044', '单条强退', '109', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1045', '任务查询', '110', '1', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query',          '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1046', '任务新增', '110', '2', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add',            '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1047', '任务修改', '110', '3', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit',           '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1048', '任务删除', '110', '4', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1049', '状态修改', '110', '5', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus',   '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('1050', '任务导出', '110', '6', '#', '', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export',         '#', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
('120',  'Telegram发送', '1', '10', '', '', '', '', 1, 0, 'F', '1', '0', 'notification:telegram:send', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, 'Telegram通知接口权限'),
('121',  'WhatsApp发送', '1', '11', '', '', '', '', 1, 0, 'F', '1', '0', 'notification:whatsapp:send', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, 'WhatsApp通知接口权限'),
('122',  '系统通知', '1', '9', 'notification', 'notification/index', '', '', 1, 0, 'C', '0', '0', 'notification:view', 'message', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统通知页面'),
('123',  'Lark发送', '122', '3', '', '', '', '', 1, 0, 'F', '1', '0', 'notification:lark:send', '#', 'admin', CURRENT_TIMESTAMP, '', NULL, 'Lark通知接口权限'),
('124',  '数据监控', '2', '1', 'doris', 'monitor/doris/index', '', '', 1, 0, 'C', '0', '0', 'monitor:doris:query', 'data-analysis', 'admin', CURRENT_TIMESTAMP, '', NULL, 'Doris数据监控');

-- 6. 菜单多语言表
-- SysMenuMapper 会在查询菜单时关联本表；必须在应用启动前创建。
CREATE TABLE sys_menu_i18n (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  menu_id     BIGINT NOT NULL,
  locale      VARCHAR(20) NOT NULL,
  menu_name   VARCHAR(100) NOT NULL,
  remark      VARCHAR(500) DEFAULT '',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_sys_menu_i18n_menu_locale UNIQUE (menu_id, locale),
  CONSTRAINT fk_sys_menu_i18n_menu FOREIGN KEY (menu_id)
    REFERENCES sys_menu(menu_id) ON DELETE CASCADE
);
COMMENT ON TABLE sys_menu_i18n IS '菜单多语言名称表：支持 zh-CN、zh-TW 和 en-US 菜单展示';

INSERT INTO sys_menu_i18n (menu_id, locale, menu_name, remark)
VALUES
  (1,   'zh-CN', '系统管理', '系统管理目录'),
  (1,   'zh-TW', '系統管理', '系統管理目錄'),
  (1,   'en-US', 'System Management', 'System management'),
  (2,   'zh-CN', '系统监控', '系统监控目录'),
  (2,   'zh-TW', '系統監控', '系統監控目錄'),
  (2,   'en-US', 'System Monitoring', 'System monitoring'),
  (100, 'zh-CN', '用户管理', '用户管理菜单'),
  (100, 'zh-TW', '使用者管理', '使用者管理選單'),
  (100, 'en-US', 'User Management', 'User management'),
  (101, 'zh-CN', '角色管理', '角色管理菜单'),
  (101, 'zh-TW', '角色管理', '角色管理選單'),
  (101, 'en-US', 'Role Management', 'Role management'),
  (102, 'zh-CN', '权限管理', '权限管理菜单'),
  (102, 'zh-TW', '權限管理', '權限管理選單'),
  (102, 'en-US', 'Permission Management', 'Permission management'),
  (103, 'zh-CN', '部门管理', '部门管理菜单'),
  (103, 'zh-TW', '部門管理', '部門管理選單'),
  (103, 'en-US', 'Department Management', 'Department management'),
  (108, 'zh-CN', '日志管理', '日志管理菜单'),
  (108, 'zh-TW', '日誌管理', '日誌管理選單'),
  (108, 'en-US', 'Log Management', 'Log management'),
  (118, 'zh-CN', '权限总览', '权限总览菜单'),
  (118, 'zh-TW', '權限總覽', '權限總覽選單'),
  (118, 'en-US', 'Permission Overview', 'Permission overview'),
  (122, 'zh-CN', '系统通知', '系统通知菜单'),
  (122, 'zh-TW', '系統通知', '系統通知選單'),
  (122, 'en-US', 'System Notifications', 'System notifications'),
  (124, 'zh-CN', '数据监控', 'Doris数据监控菜单'),
  (124, 'zh-TW', '資料監控', 'Doris資料監控選單'),
  (124, 'en-US', 'Data Monitoring', 'Doris data monitoring'),
  (500, 'zh-CN', '操作日志', '操作日志菜单'),
  (500, 'zh-TW', '操作日誌', '操作日誌選單'),
  (500, 'en-US', 'Operation Logs', 'Operation logs'),
  (501, 'zh-CN', '登录日志', '登录日志菜单'),
  (501, 'zh-TW', '登入日誌', '登入日誌選單'),
  (501, 'en-US', 'Login Logs', 'Login logs');

-- 6. 用户和角色关联表
CREATE TABLE sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户和角色关联表';
INSERT INTO sys_user_role VALUES ('1', '1'), ('2', '2');

-- 7. 角色和菜单关联表
CREATE TABLE sys_role_menu (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, menu_id)
);
COMMENT ON TABLE sys_role_menu IS '角色和菜单关联表';

-- 普通角色仅保留基础查看权限，不允许新增、修改、删除、导入、重置密码、角色/权限配置或系统配置。
INSERT INTO sys_role_menu VALUES
('2', '1'), ('2', '2'), ('2', '100'), ('2', '103'),
('2', '108'), ('2', '500'), ('2', '501'),
('2', '1000'), ('2', '1016'),
('2', '1035'), ('2', '1038');

-- 8. 角色和部门关联表
CREATE TABLE sys_role_dept (
  role_id BIGINT NOT NULL,
  dept_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, dept_id)
);
COMMENT ON TABLE sys_role_dept IS '角色和部门关联表';
INSERT INTO sys_role_dept VALUES ('2', '100'), ('2', '101'), ('2', '105');

-- 9. 用户与岗位关联表
CREATE TABLE sys_user_post (
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, post_id)
);
COMMENT ON TABLE sys_user_post IS '用户与岗位关联表';
INSERT INTO sys_user_post VALUES ('1', '1'), ('2', '2');

-- 10. 操作日志记录
CREATE TABLE sys_oper_log (
  oper_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  title          VARCHAR(50) DEFAULT '',
  business_type  INTEGER DEFAULT 0,
  method         VARCHAR(200) DEFAULT '',
  request_method VARCHAR(10) DEFAULT '',
  operator_type  INTEGER DEFAULT 0,
  oper_name      VARCHAR(50) DEFAULT '',
  dept_name      VARCHAR(50) DEFAULT '',
  oper_url       VARCHAR(255) DEFAULT '',
  oper_ip        VARCHAR(128) DEFAULT '',
  oper_location  VARCHAR(255) DEFAULT '',
  oper_param     VARCHAR(2000) DEFAULT '',
  json_result    VARCHAR(2000) DEFAULT '',
  status         INTEGER DEFAULT 0,
  error_msg      VARCHAR(2000) DEFAULT '',
  oper_time      TIMESTAMP,
  cost_time      BIGINT DEFAULT 0,
  PRIMARY KEY (oper_id)
);
COMMENT ON TABLE sys_oper_log IS '操作日志记录';
CREATE INDEX idx_sys_oper_log_bt ON sys_oper_log (business_type);
CREATE INDEX idx_sys_oper_log_s  ON sys_oper_log (status);
CREATE INDEX idx_sys_oper_log_ot ON sys_oper_log (oper_time);

-- 11. 字典类型表
CREATE TABLE sys_dict_type (
  dict_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dict_name   VARCHAR(100) DEFAULT '',
  dict_type   VARCHAR(100) DEFAULT '',
  status      CHAR(1) DEFAULT '0',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (dict_id),
  UNIQUE (dict_type)
);
COMMENT ON TABLE sys_dict_type IS '字典类型表';

INSERT INTO sys_dict_type VALUES
(1,  '用户性别', 'sys_user_sex',        '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '用户性别列表'),
(2,  '菜单状态', 'sys_show_hide',       '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '菜单状态列表'),
(3,  '系统开关', 'sys_normal_disable',  '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统开关列表'),
(4,  '任务状态', 'sys_job_status',      '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '任务状态列表'),
(5,  '任务分组', 'sys_job_group',       '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '任务分组列表'),
(6,  '系统是否', 'sys_yes_no',          '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统是否列表'),
(9,  '操作类型', 'sys_oper_type',       '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '操作类型列表'),
(10, '系统状态', 'sys_common_status',   '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '登录状态列表');

-- 12. 字典数据表
CREATE TABLE sys_dict_data (
  dict_code   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  dict_sort   INTEGER DEFAULT 0,
  dict_label  VARCHAR(100) DEFAULT '',
  dict_value  VARCHAR(100) DEFAULT '',
  dict_type   VARCHAR(100) DEFAULT '',
  css_class   VARCHAR(100) DEFAULT NULL,
  list_class  VARCHAR(100) DEFAULT NULL,
  is_default  CHAR(1) DEFAULT 'N',
  status      CHAR(1) DEFAULT '0',
  create_by   VARCHAR(64) DEFAULT '',
  create_time TIMESTAMP,
  update_by   VARCHAR(64) DEFAULT '',
  update_time TIMESTAMP,
  remark      VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (dict_code)
);
COMMENT ON TABLE sys_dict_data IS '字典数据表';

INSERT INTO sys_dict_data VALUES
(1,  1,  '男',       '0',       'sys_user_sex',        '',   '',        'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '性别男'),
(2,  2,  '女',       '1',       'sys_user_sex',        '',   '',        'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '性别女'),
(3,  3,  '未知',     '2',       'sys_user_sex',        '',   '',        'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '性别未知'),
(4,  1,  '显示',     '0',       'sys_show_hide',       '',   'primary', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '显示菜单'),
(5,  2,  '隐藏',     '1',       'sys_show_hide',       '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '隐藏菜单'),
(6,  1,  '正常',     '0',       'sys_normal_disable',  '',   'primary', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '正常状态'),
(7,  2,  '停用',     '1',       'sys_normal_disable',  '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '停用状态'),
(8,  1,  '正常',     '0',       'sys_job_status',      '',   'primary', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '正常状态'),
(9,  2,  '暂停',     '1',       'sys_job_status',      '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '停用状态'),
(10, 1,  '默认',     'DEFAULT', 'sys_job_group',       '',   '',        'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '默认分组'),
(11, 2,  '系统',     'SYSTEM',  'sys_job_group',       '',   '',        'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统分组'),
(12, 1,  '是',       'Y',       'sys_yes_no',          '',   'primary', 'Y', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统默认是'),
(13, 2,  '否',       'N',       'sys_yes_no',          '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '系统默认否'),
(18, 99, '其他',     '0',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '其他操作'),
(19, 1,  '新增',     '1',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '新增操作'),
(20, 2,  '修改',     '2',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '修改操作'),
(21, 3,  '删除',     '3',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '删除操作'),
(22, 4,  '授权',     '4',       'sys_oper_type',       '',   'primary', 'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '授权操作'),
(23, 5,  '导出',     '5',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '导出操作'),
(24, 6,  '导入',     '6',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '导入操作'),
(25, 7,  '强退',     '7',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '强退操作'),
(26, 8,  '生成代码', '8',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '生成操作'),
(27, 9,  '清空数据', '9',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '清空操作'),
(28, 1,  '成功',     '0',       'sys_common_status',   '',   'primary', 'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '正常状态'),
(29, 2,  '失败',     '1',       'sys_common_status',   '',   'danger',  'N', '0', 'admin', CURRENT_TIMESTAMP, '', NULL, '停用状态');

-- 13. 参数配置表
CREATE TABLE sys_config (
  config_id    INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  config_name  VARCHAR(100) DEFAULT '',
  config_key   VARCHAR(100) DEFAULT '',
  config_value VARCHAR(500) DEFAULT '',
  config_type  CHAR(1) DEFAULT 'N',
  create_by    VARCHAR(64) DEFAULT '',
  create_time  TIMESTAMP,
  update_by    VARCHAR(64) DEFAULT '',
  update_time  TIMESTAMP,
  remark       VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (config_id)
);
COMMENT ON TABLE sys_config IS '参数配置表';

INSERT INTO sys_config VALUES
(1, '主框架页-默认皮肤样式名称',     'sys.index.skinName',               'skin-blue',     'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow'),
(2, '用户管理-账号初始密码',         'sys.user.initPassword',            '123456',        'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '初始化密码 123456'),
(3, '主框架页-侧边栏主题',           'sys.index.sideTheme',              'theme-dark',    'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '深色主题theme-dark，浅色主题theme-light'),
(6, '用户登录-黑名单列表',           'sys.login.blackIPList',            '',              'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）'),
(7, '用户管理-初始密码修改策略',     'sys.account.initPasswordModify',   '1',             'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '0：初始密码修改策略关闭，没有任何提示，1：提醒用户，如果未修改初始密码，则在登录时就会提醒修改密码对话框'),
(8, '用户管理-账号密码更新周期',     'sys.account.passwordValidateDays', '0',             'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '密码更新周期（填写数字，数据初始化值为0不限制，若修改必须为大于0小于365的正整数），如果超过这个周期登录系统时，则在登录时就会提醒修改密码对话框'),
(9, '用户管理-密码字符范围',         'sys.account.chrtype',              '0',             'Y', 'admin', CURRENT_TIMESTAMP, '', NULL, '默认任意字符范围，0任意（密码可以输入任意字符），1数字（密码只能为0-9数字），2英文字母（密码只能为a-z和A-Z字母），3字母和数字（密码必须包含字母，数字）,4字母数字和特殊字符（目前支持的特殊字符包括：~!@#$%^&*()-=_+）');

-- 14. 系统访问记录
CREATE TABLE sys_logininfor (
  info_id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  user_name      VARCHAR(50) DEFAULT '',
  ipaddr         VARCHAR(128) DEFAULT '',
  login_location VARCHAR(255) DEFAULT '',
  browser        VARCHAR(50) DEFAULT '',
  os             VARCHAR(50) DEFAULT '',
  status         CHAR(1) DEFAULT '0',
  msg            VARCHAR(255) DEFAULT '',
  login_time     TIMESTAMP,
  PRIMARY KEY (info_id)
);
COMMENT ON TABLE sys_logininfor IS '系统访问记录';
CREATE INDEX idx_sys_logininfor_s  ON sys_logininfor (status);
CREATE INDEX idx_sys_logininfor_lt ON sys_logininfor (login_time);

-- 15. 定时任务调度表
CREATE TABLE sys_job (
  job_id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
  job_name        VARCHAR(64) DEFAULT '',
  job_group       VARCHAR(64) DEFAULT 'DEFAULT',
  invoke_target   VARCHAR(500) NOT NULL,
  cron_expression VARCHAR(255) DEFAULT '',
  misfire_policy  VARCHAR(20) DEFAULT '3',
  concurrent      CHAR(1) DEFAULT '1',
  status          CHAR(1) DEFAULT '0',
  create_by       VARCHAR(64) DEFAULT '',
  create_time     TIMESTAMP,
  update_by       VARCHAR(64) DEFAULT '',
  update_time     TIMESTAMP,
  remark          VARCHAR(500) DEFAULT '',
  PRIMARY KEY (job_id, job_name, job_group)
);
COMMENT ON TABLE sys_job IS '定时任务调度表';

INSERT INTO sys_job VALUES
(1, '系统默认（无参）', 'DEFAULT', 'ryTask.ryNoParams',        '0/10 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
(2, '系统默认（有参）', 'DEFAULT', 'ryTask.ryParams(''ry'')',  '0/15 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '', NULL, ''),
(3, '系统默认（多参）', 'DEFAULT', 'ryTask.ryMultipleParams(''ry'', true, 2000L, 316.50D, 100)', '0/20 * * * * ?', '3', '1', '1', 'admin', CURRENT_TIMESTAMP, '', NULL, '');

-- 16. 定时任务调度日志表
CREATE TABLE sys_job_log (
  job_log_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  job_name       VARCHAR(64) NOT NULL,
  job_group      VARCHAR(64) NOT NULL,
  invoke_target  VARCHAR(500) NOT NULL,
  job_message    VARCHAR(500),
  status         CHAR(1) DEFAULT '0',
  exception_info VARCHAR(2000) DEFAULT '',
  start_time     TIMESTAMP,
  end_time       TIMESTAMP,
  create_time    TIMESTAMP,
  PRIMARY KEY (job_log_id)
);
COMMENT ON TABLE sys_job_log IS '定时任务调度日志表';

-- Permission Center 一期清理
-- 初始化完成后删除不在一期范围内的菜单、子菜单及角色授权。
WITH RECURSIVE obsolete_menu AS (
    SELECT menu_id
    FROM sys_menu
    WHERE menu_id IN (113, 114)
       OR menu_name IN (
           '系统工具', '表单构建', '系统接口',
           '通知公告', '缓存监控', '缓存列表',
           '在线用户', '定时任务', '服务器监控', 'Druid监控',
           '岗位管理', '参数设置', '字典管理'
       )
       OR path IN (
           'tool', 'build', 'swagger', 'notice', 'cache', 'cacheList',
           'online', 'job', 'server', 'druid', 'post', 'config', 'dict'
       )
    UNION
    SELECT child.menu_id
    FROM sys_menu child
    JOIN obsolete_menu parent ON child.parent_id = parent.menu_id
)
DELETE FROM sys_role_menu
WHERE menu_id IN (SELECT menu_id FROM obsolete_menu);

WITH RECURSIVE obsolete_menu AS (
    SELECT menu_id
    FROM sys_menu
    WHERE menu_id IN (113, 114)
       OR menu_name IN (
           '系统工具', '表单构建', '系统接口',
           '通知公告', '缓存监控', '缓存列表',
           '在线用户', '定时任务', '服务器监控', 'Druid监控',
           '岗位管理', '参数设置', '字典管理'
       )
       OR path IN (
           'tool', 'build', 'swagger', 'notice', 'cache', 'cacheList',
           'online', 'job', 'server', 'druid', 'post', 'config', 'dict'
       )
    UNION
    SELECT child.menu_id
    FROM sys_menu child
    JOIN obsolete_menu parent ON child.parent_id = parent.menu_id
)
DELETE FROM sys_menu
WHERE menu_id IN (SELECT menu_id FROM obsolete_menu);

-- Reset identity sequences after explicit seed IDs so later inserts cannot reuse
-- an existing primary key.
ALTER TABLE sys_dept       ALTER COLUMN dept_id     RESTART WITH 200;
ALTER TABLE sys_user       ALTER COLUMN user_id     RESTART WITH 100;
ALTER TABLE sys_post       ALTER COLUMN post_id     RESTART WITH 100;
ALTER TABLE sys_role       ALTER COLUMN role_id     RESTART WITH 100;
ALTER TABLE sys_menu       ALTER COLUMN menu_id     RESTART WITH 2000;
ALTER TABLE sys_menu_i18n  ALTER COLUMN id          RESTART WITH 100;
ALTER TABLE sys_oper_log   ALTER COLUMN oper_id     RESTART WITH 100;
ALTER TABLE sys_dict_type  ALTER COLUMN dict_id     RESTART WITH 100;
ALTER TABLE sys_dict_data  ALTER COLUMN dict_code   RESTART WITH 100;
ALTER TABLE sys_config     ALTER COLUMN config_id   RESTART WITH 100;
ALTER TABLE sys_logininfor ALTER COLUMN info_id     RESTART WITH 100;
ALTER TABLE sys_job        ALTER COLUMN job_id      RESTART WITH 100;
ALTER TABLE sys_job_log    ALTER COLUMN job_log_id  RESTART WITH 100;
